# -*- coding: utf-8 -*-
"""RSA Enc Dec.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gI0LN_mrrDgDGiRGTFC8OY4alaRV-TEF
"""

# Simple RSA Encryption and Decryption (Educational)

import math
# Function to find GCD
def gcd(a, b):
    while b != 0:
        a, b = b, a % b
    return a

# Function to find modular inverse
def mod_inverse(e, phi):
    for d in range(2, phi):
        if (d * e) % phi == 1:
            return d

# Step 1: Choose two prime numbers
p = 61
q = 53

# Step 2: Calculate n
n = p * q
# Step 3: Calculate Euler's function
phi = (p - 1) * (q - 1)

# Step 4: Choose public key exponent
e = 17

# Check gcd
if gcd(e, phi) != 1:
    print("Invalid public key")
else:

    # Step 5: Calculate private key
    d = mod_inverse(e, phi)

    print("Public Key:")
    print("(e =", e, ", n =", n, ")")

    print("\nPrivate Key:")
    print("(d =", d, ", n =", n, ")")

    # Encryption
    message = int(input("\nEnter a number to encrypt: "))

    encrypted_message = (message ** e) % n

    print("\nEncrypted Message:")
    print(encrypted_message)


    # Decryption
    decrypted_message = (encrypted_message ** d) % n

    print("\nDecrypted Message:")
    print(decrypted_message)